name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USER: kevinjennison1
      SELENIUM_DRIVER_TYPE: remote
      SELENIUM_HOST: https://test-tab2017.gladly.io
      # A unique build identifier passed to tab-e2e.
      TRAVIS_BUILD_NUMBER: tab-e2e-${{ github.run_number }}
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and build on Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn run test
