name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and build on Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    # TODO: run tests (need to set env vars first)
    - run: yarn run lint
