name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USER: kevinjennison1
      BROWSERSTACK_KEY: ${{secrets.BROWSERSTACK_KEY}}
      INTEGRATION_TEST_USER_EMAIL: ${{secrets.INTEGRATION_TEST_USER_EMAIL}}
      INTEGRATION_TEST_USER_PASSWORD: ${{secrets.INTEGRATION_TEST_USER_PASSWORD}}
      MAILOSAUR_SERVER_ID: ${{secrets.MAILOSAUR_SERVER_ID}}
      MAILOSAUR_API_KEY: ${{secrets.MAILOSAUR_API_KEY}}
      SELENIUM_DRIVER_TYPE: remote
      SELENIUM_HOST: https://test-tab2017.gladly.io
      # A unique build identifier passed to tab-e2e.
      TRAVIS_BUILD_NUMBER: tab-e2e-${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn run build
      - run: yarn run test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
